### ISSUE TITLE
Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

### ISSUE THREAD

**Issue by wssy001** [kazuki43zoo/mybatis-native-demo#2]
## Environment:
- SpringBoot: 3.0.6
- GraalVM: GraalVM 22.3.1 Java 19 EE
- mybatis-spring-boot-starter: 3.0.1

Erorr log:
[error.log](https://github.com/kazuki43zoo/mybatis-native-demo/files/11417184/error.log)
My test project:
https://github.com/wssy001/test-native

I also tested my project by using AOT Tracing, still failed in Native Image mode.

**Comment by cadb-craftsman** [comment]
Hi 

I solve this problem with the creation of sessionFactory and sessionTemplate, if you want to see my code this is my github repo.

https://github.com/cadb-craftsman/springboot-labs.git

the project is catalogsvc

Greetings

**Comment by kazuki43zoo** [comment]
@wssy001 

If you use the `@MapperScan`, you should be specified either the `sqlSessionTemplateRef` or `sqlSessionFactoryRef` as follows:

```java
@MapperScan(basePackages = "com.example.testnative", sqlSessionTemplateRef = "sqlSessionTemplate")
@SpringBootApplication(proxyBeanMethods = false)
public class TestNativeApplication {
  // ...
}
```

**Comment by kazuki43zoo** [comment]
@wssy001 

If you use the mbatis-spring-boot-starter, I recommend to specify the `@Mapper` on your mapper interface. that way you can omit the `@MapperScan`.

**Comment by wssy001** [comment]
> Hi
> 
> I solve this problem with the creation of sessionFactory and sessionTemplate, if you want to see my code this is my github repo.
> 
> https://github.com/cadb-craftsman/springboot-labs.git
> 
> the project is catalogsvc
> 
> Greetings

I will see later

**Comment by wssy001** [comment]
> If you use the `@MapperScan`, you should be specified either the `sqlSessionTemplateRef` or `sqlSessionFactoryRef` as follows:
> 
> ```java
> @MapperScan(basePackages = "com.example.testnative", sqlSessionTemplateRef = "sqlSessionTemplate")
> @SpringBootApplication(proxyBeanMethods = false)
> public class TestNativeApplication {
>   // ...
> }
> ```

it did work !

**Comment by lihuagang03** [comment]
> @wssy001
> 
> If you use the mbatis-spring-boot-starter, I recommend to specify the `@Mapper` on your mapper interface. that way you can omit the `@MapperScan`.

This might work, you can try it.  @wssy001 

```java
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

import com.example.ai.message.repository.model.GptModelRequestTask;

import org.apache.ibatis.annotations.Mapper;

/**
 * 模型请求任务映射器
 *
 * @see com.baomidou.mybatisplus.core.mapper.BaseMapper
 */
@Mapper
public interface GptModelRequestTaskMapper extends BaseMapper<GptModelRequestTask> {
    //
}

```

**Comment by wssy001** [comment]
> > @wssy001
> > If you use the mbatis-spring-boot-starter, I recommend to specify the `@Mapper` on your mapper interface. that way you can omit the `@MapperScan`.
> 
> This might work, can try it. @wssy001
> 
> ```java
> import com.baomidou.mybatisplus.core.mapper.BaseMapper;
> 
> import com.example.ai.message.repository.model.GptModelRequestTask;
> 
> import org.apache.ibatis.annotations.Mapper;
> 
> /**
>  * 模型请求任务映射器
>  *
>  * @see com.baomidou.mybatisplus.core.mapper.BaseMapper
>  */
> @Mapper
> public interface GptModelRequestTaskMapper extends BaseMapper<GptModelRequestTask> {
>     //
> }
> ```

works too
